language: python
sudo: true
addons:
    postgresql: "9.6"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "3.7-dev"
    - python: "3.8-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install coveralls
  - pip install -r requirements.test.txt
  - pip install python-coveralls
  - pip install -U pytest pytest-cov

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_product
  - psql -c 'create database travis_ci_test;' -U postgres
  - py.test anyblok_product/tests
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb -c tests.cfg --test-blok-at-install
  - psql -c 'drop database anyblok_product_test;' -U postgres

after_success:
  coveralls
